### ISSUE TITLE
Simplify Kafka Local Setup to Leverage KRaft Instead of Zookeeper

### ISSUE THREAD

**Issue by olga-casian** [yonatankarp/xkcd-data-hub#43]
Update the local Kafka setup to use KRaft (Kafka Raft Metadata mode) instead of Zookeeper for a more lightweight and simplified execution environment. This will streamline the local development process and reduce the overhead associated with running a separate Zookeeper instance.

**Tasks:**

1. **Update Docker Compose Configuration:**
   - Modify the Docker Compose file to configure Kafka to use KRaft mode.
   - Remove the Zookeeper configuration from the setup.

2. **Configure Kafka for KRaft Mode:**
   - Update Kafka configuration to enable KRaft mode.
   - Set necessary KRaft-related parameters such as `process.roles`, `node.id`, and `controller.quorum.voters`.

3. **Test the KRaft Setup:**
   - Ensure Kafka starts correctly in KRaft mode.
   - Validate that the Fetcher and Data Processor services can connect to Kafka and operate as expected.

4. **Update Documentation:**
   - Modify the setup instructions in the README to reflect the changes to the Kafka configuration.
   - Provide guidance on running Kafka in KRaft mode for local development.

**Updated Docker Compose File Example by ChatGPT:**

```yaml
version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    volumes:
      - ./kafka-data:/var/lib/kafka/data
```

**Acceptance Criteria:**

- Kafka is running in KRaft mode without Zookeeper.
- Fetcher and Data Processor services work correctly with Kafka in KRaft mode.
- Updated README with revised setup instructions.
